# Generated by Django 2.2 on 2020-05-18 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_stockitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateCreated', models.DateTimeField(auto_now_add=True)),
                ('Value', models.FloatField(default=0, verbose_name='Discount Quantity')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Page', models.CharField(max_length=30)),
                ('Code', models.CharField(max_length=30, unique=True)),
                ('Address', models.CharField(max_length=30, unique=True)),
                ('Unit', models.CharField(max_length=10)),
                ('DateCreated', models.DateTimeField(auto_now_add=True)),
                ('LastEdit', models.DateTimeField(auto_now=True)),
                ('Data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.LogData')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='Collect',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Outlet',
        ),
        migrations.RemoveField(
            model_name='order',
            name='POC',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Return',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='Item',
        ),
        migrations.RemoveField(
            model_name='outlet',
            name='Agent',
        ),
        migrations.RemoveField(
            model_name='outlet',
            name='Products',
        ),
        migrations.RemoveField(
            model_name='returnitem',
            name='Item',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='Item',
        ),
        migrations.RemoveField(
            model_name='account',
            name='email',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_manager',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_salesman',
        ),
        migrations.DeleteModel(
            name='CollectItem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='outlet',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ReturnItem',
        ),
        migrations.DeleteModel(
            name='StockItem',
        ),
    ]
