# Generated by Django 2.2 on 2020-05-20 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200518_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Page', models.CharField(max_length=30)),
                ('Code', models.CharField(max_length=30, unique=True)),
                ('Address', models.CharField(max_length=30, unique=True)),
                ('Unit', models.CharField(max_length=10)),
                ('DateCreated', models.DateTimeField(auto_now_add=True)),
                ('LastEdit', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Machine',
        ),
        migrations.AddField(
            model_name='logdata',
            name='Machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.MachineData'),
        ),
    ]
