# Generated by Django 2.2 on 2020-05-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200520_0251'),
    ]

    operations = [
        migrations.CreateModel(
            name='IOTDev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateCreated', models.DateTimeField(auto_now_add=True)),
                ('Site', models.CharField(max_length=30)),
                ('Passport', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='logdata',
            name='Value',
            field=models.FloatField(default=0),
        ),
    ]
