# Generated by Django 2.2 on 2020-05-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200520_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotdev',
            name='CSRFTok',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='iotdev',
            name='Site',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
