# Generated by Django 2.2 on 2020-05-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200521_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinedata',
            name='Dev',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
