# Generated by Django 2.2 on 2020-05-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_machinedata_dev'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinedata',
            name='Line',
            field=models.CharField(default='Line1', max_length=30),
            preserve_default=False,
        ),
    ]
