# Generated by Django 2.2 on 2020-05-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_useraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinedata',
            name='IP',
            field=models.CharField(default='192.168.1.222', max_length=20),
            preserve_default=False,
        ),
    ]
