# Generated by Django 2.2 on 2020-05-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_machinedata_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinedata',
            name='Address',
            field=models.CharField(max_length=30),
        ),
    ]
