# Generated by Django 2.2 on 2020-05-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200528_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msg',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
