# Generated by Django 2.2 on 2020-09-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200528_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinedata',
            name='Name',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
    ]
