# Generated by Django 2.2 on 2020-09-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_machinedata_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinedata',
            name='low_limit',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machinedata',
            name='upper_limit',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
