# Generated by Django 2.2 on 2020-09-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200910_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinedata',
            name='Parameter',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
