# Generated by Django 3.1.1 on 2020-10-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_machinedata_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinedata',
            name='Value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
