# Generated by Django 2.2 on 2020-10-22 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_machinedata_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logdata',
            name='Value',
        ),
        migrations.RemoveField(
            model_name='machinedata',
            name='Line',
        ),
        migrations.RemoveField(
            model_name='machinedata',
            name='Parameter',
        ),
        migrations.RemoveField(
            model_name='machinedata',
            name='Unit',
        ),
        migrations.RemoveField(
            model_name='machinedata',
            name='low_limit',
        ),
        migrations.RemoveField(
            model_name='machinedata',
            name='upper_limit',
        ),
        migrations.AddField(
            model_name='logdata',
            name='AckTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='logdata',
            name='CompleteTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='logdata',
            name='Event',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='logdata',
            name='LastUpdate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='logdata',
            name='PIC',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logdata',
            name='Status',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='logdata',
            name='DateCreated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='logdata',
            name='Machine',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.MachineData'),
            preserve_default=False,
        ),
    ]
