# Generated by Django 2.2 on 2020-10-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20201022_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinedata',
            name='Value',
            field=models.IntegerField(default=0),
        ),
    ]
