# Generated by Django 2.2 on 2020-10-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20201023_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinedata',
            name='Status',
            field=models.IntegerField(default=0),
        ),
    ]
