# Generated by Django 2.2 on 2020-10-23 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_machinedata_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinedata',
            name='Site',
            field=models.CharField(default='Panasonic PIDMY', max_length=50),
            preserve_default=False,
        ),
    ]
