# Generated by Django 2.2 on 2020-10-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_machinedata_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Site',
            field=models.CharField(default='PIDMY', max_length=40, null=True),
        ),
    ]
