# Generated by Django 2.2 on 2020-10-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_account_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdata',
            name='PIC',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
