# Generated by Django 2.2 on 2020-10-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20201023_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdata',
            name='AckTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logdata',
            name='CompleteTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logdata',
            name='PIC',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
