# Generated by Django 3.1.2 on 2020-10-31 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20201023_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='Site',
        ),
    ]
