# Generated by Django 3.1.2 on 2020-10-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_remove_account_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='Messages',
        ),
        migrations.AddField(
            model_name='account',
            name='amount',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='bank_account',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='deposit',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='duration',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='profit',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
