# Generated by Django 3.1.2 on 2020-10-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20201031_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='amount',
            field=models.CharField(default='0', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='bank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='bank_account',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='deposit',
            field=models.CharField(default='0', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='duration',
            field=models.CharField(default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='profit',
            field=models.CharField(default='0', max_length=15, null=True),
        ),
    ]
