# Generated by Django 3.1.2 on 2020-11-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_profit', models.CharField(max_length=15)),
                ('average_return_of_investment', models.CharField(max_length=15)),
                ('total_investment_profit', models.CharField(max_length=15)),
                ('total_investment_contra', models.CharField(max_length=15)),
                ('total_investment_lost', models.CharField(max_length=15)),
            ],
        ),
    ]
