# Generated by Django 3.1.2 on 2020-11-01 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_portfolio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolio',
            new_name='Portfolio_data',
        ),
    ]
