# Generated by Django 3.1.2 on 2020-11-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20201101_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founded', models.CharField(max_length=15)),
                ('header', models.CharField(max_length=250)),
                ('topic1', models.CharField(max_length=500)),
                ('body1', models.CharField(max_length=500)),
                ('topic2', models.CharField(max_length=500)),
                ('body2', models.CharField(max_length=500)),
            ],
        ),
    ]
