# Generated by Django 3.1.2 on 2020-11-02 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_auto_20201102_1722'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTransactions',
            new_name='UserTransaction',
        ),
    ]
